apiVersion: v2
name: hatchery
description: Game server hosting on Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.30.0-0"
home: https://github.com/kevinfinalboss/Hatchery
