---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - limitranges
  - namespaces
  - persistentvolumeclaims
  - pods
  - resourcequotas
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gameservers.hatchery.io
  resources:
  - eggs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gameservers.hatchery.io
  resources:
  - gameserverbackups
  - gameserverrestores
  - gameservers
  - tenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gameservers.hatchery.io
  resources:
  - gameserverbackups/finalizers
  - gameserverrestores/finalizers
  - gameservers/finalizers
  - tenants/finalizers
  verbs:
  - update
- apiGroups:
  - gameservers.hatchery.io
  resources:
  - gameserverbackups/status
  - gameserverrestores/status
  - gameservers/status
  - tenants/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  - tcproutes
  - udproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - hatchery-panel-catalog
  - hatchery-panel-tenant
  resources:
  - clusterroles
  verbs:
  - bind
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
