resources:
- bases/gameservers.hatchery.io_eggs.yaml
- bases/gameservers.hatchery.io_gameservers.yaml
- bases/gameservers.hatchery.io_gameserverbackups.yaml
- bases/gameservers.hatchery.io_gameserverrestores.yaml
- bases/gameservers.hatchery.io_gameserverschedules.yaml
- bases/gameservers.hatchery.io_tenants.yaml

patches:
